collections:
  - name: redhat_cop.tower_configuration
    version: 1.4.1
    #source: https://galaxy.ansible.com

  - name: ansible.tower
    version: 3.8.1
    #source: https://cloud.redhat.com/api/automation-hub/