- name: Create an RHPDS Sandbox
  hosts: localhost
  vars:
    - tower_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    - tower_oauthtoken: "{{ lookup('env', 'TOWER_OAUTHTOKEN') }}"
  collections:
    - ansible.tower
    #- awx.awx
    - redhat_cop.tower_configuration

  pre_tasks:
    - name: Include vars from vars directory
      include_vars:
        file: ./vars/base.yml

  roles:
      - { role: check_vars }
      - { role: rhpds, when: cfme_url is defined }

  tasks:
  - name: Add AWS RHPDS Credential to Tower
    tower_credential:
      name: "{{ credential_name }}"
      description: RHPDS AWS Token
      organization: "{{ tower_org }}"
      credential_type: Amazon Web Services
      inputs:
        username: "{{ aws_access_key | default('access') }}"
        password: "{{ aws_access_secret | default('secret') }}"
      tower_oauthtoken: "{{ tower_oauthtoken | default(omit, true) }}"
      tower_host: "{{ tower_hostname }}"