- name: Playbook to create a Custom Credential
  hosts: localhost
  vars:
    - controller_hostname: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    - controller_oauthtoken: "{{ lookup('env', 'CONTROLLER_OAUTHTOKEN') }}"
  collections:
    - ansible.controller
    - redhat_cop.controller_configuration

  pre_tasks:
    - name: Include vars from vars directory
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/controller_credential_types.yml"
      tags:
        - always

  roles:
    - {role: credential_types, when: controller_credential_types is defined, tags: credential_types}
